Repository wave-k8s/wave, pull requests merged in 2019-09, with the labels that each got.

#64 Fix linting
  Makefile
  pkg/controller/daemonset/daemonset_controller_test.go
  pkg/controller/deployment/deployment_controller_test.go
  pkg/controller/statefulset/statefulset_controller_test.go
Labels: size/M

#65 Reset registry to reduce error messages in test output
  pkg/controller/daemonset/daemonset_controller_test.go
  pkg/controller/deployment/deployment_controller_test.go
  pkg/controller/statefulset/statefulset_controller_test.go
Labels: enhancement, size/S

#51 [IS-698] - Remove redundant Update matcher
  pkg/controller/daemonset/daemonset_controller_test.go
  pkg/controller/deployment/deployment_controller_test.go
  pkg/controller/statefulset/statefulset_controller_test.go
  pkg/core/children_test.go
  pkg/core/delete_test.go
  pkg/core/handler_test.go
  pkg/core/hash_test.go
  pkg/core/owner_references_test.go
  test/utils/matchers.go
Labels: size/L

#68 Fix typo in README.md
  README.md
Labels: ok-to-test, size/XS
