Repository wave-k8s/wave, pull requests merged in 2019-04, with the labels that each got.

#40 Copy build improvements from Faros
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  Makefile
  Makefile.tools
  config/rbac/manager_role.yaml
  config/rbac/manager_role_binding.yaml
  configure
  pkg/controller/deployment/deployment_controller.go
  pkg/core/children.go
  pkg/core/children_test.go
  pkg/core/delete_test.go
  pkg/core/handler_test.go
  pkg/core/owner_references_test.go
  test/utils/delete.go
  test/utils/matchers.go
  wercker.yml
Labels: lgtm, ok-to-test, size/XL

#38 Refactoring to support other pod controller types
  pkg/core/children.go
  pkg/core/children_test.go
  pkg/core/delete.go
  pkg/core/delete_test.go
  pkg/core/finalizer.go
  pkg/core/finalizer_test.go
  pkg/core/handler.go
  pkg/core/hash.go
  pkg/core/hash_test.go
  pkg/core/owner_references.go
  pkg/core/owner_references_test.go
  pkg/core/required_annotation.go
  pkg/core/required_annotation_test.go
  pkg/core/types.go
Labels: ok-to-test, size/L

#42 Fix build issue introduced in #40
  Gopkg.lock
  Gopkg.toml
Labels: do-not-merge/work-in-progress, size/L

#39 Fix `kustomize build` sample
  config/default/kustomization.yaml
  config/default/manager/manager.yaml
  config/default/rbac/rbac_role.yaml
  config/default/rbac/rbac_role_binding.yaml
Labels: ok-to-test, size/XS

#43 Remove wercker config
  wercker.yml
Labels: size/M

#45 Fix linting configuration
  Makefile
  pkg/controller/deployment/deployment_controller_test.go
  pkg/core/handler.go
  pkg/core/handler_test.go
  pkg/core/hash_test.go
  pkg/core/required_annotation.go
  pkg/core/required_annotation_test.go
  pkg/core/types.go
Labels: size/M

#48 Add `--version` flag
  Dockerfile
  Makefile
  cmd/manager/main.go
  cmd/manager/version.go
Labels: size/S

#49 Attempt to fix flaking tests in Deployment and StatefulSet controllers
  pkg/controller/deployment/deployment_controller_test.go
  pkg/controller/statefulset/statefulset_controller_test.go
  test/utils/matchers.go
Labels: size/L

#50 Add DaemonSet support
  config/rbac/manager_role.yaml
  pkg/controller/add_daemonset.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_controller_suite_test.go
  pkg/controller/daemonset/daemonset_controller_test.go
  pkg/core/handler.go
  pkg/core/owner_references.go
  pkg/core/types.go
  test/utils/matchers.go
  test/utils/owner_ref.go
  test/utils/test_objects.go
Labels: size/XL
